version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nextjs-material-ui
    volumes:
      - .:/home/node/app
    ports:
      - 3001:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
